export const SKSK = {};

/**
 * The set of Attribute Scores used within the system.
 * @type {Object}
 */
SKSK.attributes = {
  str: 'SKSK.Attribute.Str.long',
  dex: 'SKSK.Attribute.Dex.long',
  con: 'SKSK.Attribute.Con.long',
  per: 'SKSK.Attribute.Per.long',
  wil: 'SKSK.Attribute.Wil.long',
  aur: 'SKSK.Attribute.Aur.long',
  cha: 'SKSK.Attribute.Cha.long',
  app: 'SKSK.Attribute.App.long',
};

SKSK.speciesTypes = {
  main: 'SKSK.Species.Type.Main',
  sub: 'SKSK.Species.Type.Sub',
};

SKSK.classTypes = {
  first: 'SKSK.Class.Type.First',
  second: 'SKSK.Class.Type.Second',
  third: 'SKSK.Class.Type.Third',
  advanced: 'SKSK.Class.Type.Advanced',
};

SKSK.talentTypes = {
  level6: 'SKSK.Talent.Type.Level6',
  level12: 'SKSK.Talent.Type.Level12',
  level18: 'SKSK.Talent.Type.Level18',
  level24: 'SKSK.Talent.Type.Level24',
  mythic: 'SKSK.Talent.Type.Mythic',
  bonus: 'SKSK.Talent.Type.Bonus',
  bloodline: 'SKSK.Talent.Type.Bloodline',
};

SKSK.attributeAbbreviations = {
  str: 'SKSK.Attribute.Str.abbr',
  dex: 'SKSK.Attribute.Dex.abbr',
  con: 'SKSK.Attribute.Con.abbr',
  per: 'SKSK.Attribute.Per.abbr',
  wil: 'SKSK.Attribute.Wil.abbr',
  aur: 'SKSK.Attribute.Aur.abbr',
  cha: 'SKSK.Attribute.Cha.abbr',
  app: 'SKSK.Attribute.App.abbr',
};

SKSK.skills = {
  weapons: {
    axe: 'SKSK.Skill.Weapon.Axe',
    bow: 'SKSK.Skill.Weapon.Bow',
    bluntWeapon: 'SKSK.Skill.Weapon.BluntWeapon',
    dagger: 'SKSK.Skill.Weapon.Dagger',
    firearms: 'SKSK.Skill.Weapon.Firearms',
    martialArts: 'SKSK.Skill.Weapon.MartialArts',
    polearms: 'SKSK.Skill.Weapon.Polearms',
    sword: 'SKSK.Skill.Weapon.Sword',
  },
  armors: {
    heavyArmor: 'SKSK.Skill.Armor.HeavyArmor',
    lightArmor: 'SKSK.Skill.Armor.LightArmor',
    shield: 'SKSK.Skill.Armor.Shield',
  },
  production: {
    alchemy: 'SKSK.Skill.Crafting.Alchemy',
    crafting: 'SKSK.Skill.Crafting.Crafting',
    cooking: 'SKSK.Skill.Crafting.Cooking',
    enchanting: 'SKSK.Skill.Crafting.Enchanting',
  },
  rogue: {
    assassination: 'SKSK.Skill.Rogue.Assassination',
    traps: 'SKSK.Skill.Rogue.Traps',
    stealth: 'SKSK.Skill.Rogue.Stealth',
    sleightOfHand: 'SKSK.Skill.Rogue.SleightOfHand'
  },
  magicSchools: {
    fire: 'SKSK.SKill.MagicSchool.Fire',
    water: 'SKSK.Skill.MagicSchool.Water',
    earth: 'SKSK.Skill.MagicSchool.Earth',
    air: 'SKSK.Skill.MagicSchool.Air',
    light: 'SKSK.Skill.MagicSchool.Light',
    dark: 'SKSK.Skill.MagicSchool.Dark',
    life: 'SKSK.Skill.MagicSchool.Life',
    death: 'SKSK.Skill.MagicSchool.Death',
    trickery: 'SKSK.Skill.MagicSchool.Trickery',
    nature: 'SKSK.Skill.MagicSchool.Nature',
    bardic: 'SKSK.Skill.MagicSchool.Bardic',
    divination: 'SKSK.Skill.MagicSchool.Divination',
    space: 'SKSK.Skill.MagicSchool.Space',
    time: 'SKSK.Skill.MagicSchool.Time',
    blood: 'SKSK.Skill.MagicSchool.Blood',
  },
  magic: {
    concentration: 'SKSK.Skill.Magic.Concentration',
    meditation: 'SKSK.Skill.Magic.Meditation',
    summoning: 'SKSK.Skill.Magic.Summoning',
    magicControl: 'SKSK.Skill.Magic.Control',
    manaCapactiy: 'SKSK.Skill.Magic.ManaCapacity',
    manaRegeneration: 'SKSK.Skill.Magic.ManaRegeneration',
    manaCore: 'SKSK.Skill.Magic.ManaCore',
    ritualism: 'SKSK.Skill.Magic.Ritualism',
    chantShortening: 'SKSK.Skill.Magic.ChantShortening',
    overcharge: 'SKSK.Skill.Magic.Overcharge',
    sourceBound: 'SKSK.Skill.Magic.SourceBound',
    etherBound: 'SKSK.Skill.Magic.EtherBound',
    chantless: 'SKSK.Skill.Magic.Chantless',
  },
  fighter: {
    health: 'SKSK.Skill.Fighter.Health',
    stamina: 'SKSK.Skill.Fighter.Stamina',
    technique: 'SKSK.Skill.Fighter.Technique',
    reflexes: 'SKSK.Skill.Fighter.Reflexes',
    precision: 'SKSK.Skill.Fighter.Precision',
    brutality: 'SKSK.Skill.Fighter.Brutality',
    adrenalin: 'SKSK.Skill.Fighter.Adrenalin',
    ambidextrous: 'SKSK.Skill.Fighter.Ambidextrous',
  },
  misc: {
    observation: 'SKSK.Skill.Misc.Observation',
    faith: 'SKSK.Skill.Misc.Faith',
    rhetoric: 'SKSK.Skill.Misc.Rhetoric',
    healer: 'SKSK.Skill.Misc.Healer',
    singing: 'SKSK.Skill.Misc.Singing',
    tactic: 'SKSK.Skill.Misc.Tactic',
    survival: 'SKSK.Skill.Misc.Survival',
    disguise: 'SKSK.Skill.Misc.Disguise',
    intimidation: 'SKSK.Skill.Misc.Intimidation',
    inspiration: 'SKSK.Skill.Misc.Inspiration',
    totem: 'SKSK.Skill.Misc.Totem',
    tenacity: 'SKSK.Skill.Misc.Tenacity',
  },
  attribute: {
    unlimitedStrength: 'SKSK.Skill.Attribute.UnlimitedStrength',
    unlimitedDexterity: 'SKSK.Skill.Attribute.UnlimitedDexterity',
    unlimitedConstitution: 'SKSK.Skill.Attribute.UnlimitedConstitution',
    unlimitedPerception: 'SKSK.Skill.Attribute.UnlimitedPerception',
    unlimitedWillpower: 'SKSK.Skill.Attribute.UnlimitedWillpower',
    unlimitedAura: 'SKSK.Skill.Attribute.UnlimitedAura',
    unlimitedCharisma: 'SKSK.Skill.Attribute.UnlimitedCharisma',
    unlimitedAppearance: 'SKSK.Skill.Attribute.UnlimitedAppearance',
  },
  resistances: {
    fireResistance: 'SKSK.Skill.Resistance.FireResistance',
    waterResistance: 'SKSK.Skill.Resistance.WaterResistance',
    earthResistance: 'SKSK.Skill.Resistance.EarthResistance',
    airResistance: 'SKSK.Skill.Resistance.AirResistance',
    lightResistance: 'SKSK.Skill.Resistance.LightResistance',
    darkResistance: 'SKSK.Skill.Resistance.DarkResistance',
    lifeResistance: 'SKSK.Skill.Resistance.LifeResistance',
    deathResistance: 'SKSK.Skill.Resistance.DeathResistance',
    mentalResistance: 'SKSK.Skill.Resistance.MentalResistance',
    natureResistance: 'SKSK.Skill.Resistance.NatureResistance',
    coldResistance: 'SKSK.Skill.Resistance.ColdResistance',
    heatResistance: 'SKSK.Skill.Resistance.HeatResistance',
    bluntResistance: 'SKSK.Skill.Resistance.BluntResistance',
    sharpResistance: 'SKSK.Skill.Resistance.SharpResistance',
    piercingResistance: 'SKSK.Skill.Resistance.PiercingResistance',
    poisonResistance: 'SKSK.Skill.Resistance.PoisonResistance',
    acidResistance: 'SKSK.Skill.Resistance.AcidResistance',
    electricityResistance: 'SKSK.Skill.Resistance.ElectricityResistance',
    iceResistance: 'SKSK.Skill.Resistance.IceResistance',
  },
  immunity: {
    fireImmunity: 'SKSK.Skill.Immunity.FireImmunity',
    waterImmunity: 'SKSK.Skill.Immunity.WaterImmunity',
    earthImmunity: 'SKSK.Skill.Immunity.EarthImmunity',
    airImmunity: 'SKSK.Skill.Immunity.AirImmunity',
    lightImmunity: 'SKSK.Skill.Immunity.LightImmunity',
    darkImmunity: 'SKSK.Skill.Immunity.DarkImmunity',
    lifeImmunity: 'SKSK.Skill.Immunity.LifeImmunity',
    deathImmunity: 'SKSK.Skill.Immunity.DeathImmunity',
    mentalImmunity: 'SKSK.Skill.Immunity.MentalImmunity',
    natureImmunity: 'SKSK.Skill.Immunity.NatureImmunity',
    coldImmunity: 'SKSK.Skill.Immunity.ColdImmunity',
    heatImmunity: 'SKSK.Skill.Immunity.HeatImmunity',
    bluntImmunity: 'SKSK.Skill.Immunity.BluntImmunity',
    sharpImmunity: 'SKSK.Skill.Immunity.SharpImmunity',
    piercingImmunity: 'SKSK.Skill.Immunity.PiercingImmunity',
    poisonImmunity: 'SKSK.Skill.Immunity.PoisonImmunity',
    acidImmunity: 'SKSK.Skill.Immunity.AcidImmunity',
    electricityImmunity: 'SKSK.Skill.Immunity.ElectricityImmunity',
    iceImmunity: 'SKSK.Skill.Immunity.IceImmunity',
  },
  absorb: {
    fireAbsorption: 'SKSK.Skill.Absorb.FireAbsorption',
    waterAbsorption: 'SKSK.Skill.Absorb.WaterAbsorption',
    earthAbsorption: 'SKSK.Skill.Absorb.EarthAbsorption',
    airAbsorption: 'SKSK.Skill.Absorb.AirAbsorption',
    lightAbsorption: 'SKSK.Skill.Absorb.LightAbsorption',
    darkAbsorption: 'SKSK.Skill.Absorb.DarkAbsorption',
    lifeAbsorption: 'SKSK.Skill.Absorb.LifeAbsorption',
    deathAbsorption: 'SKSK.Skill.Absorb.DeathAbsorption',
    mentalAbsorption: 'SKSK.Skill.Absorb.MentalAbsorption',
    natureAbsorption: 'SKSK.Skill.Absorb.NatureAbsorption',
    coldAbsorption: 'SKSK.Skill.Absorb.ColdAbsorption',
    heatAbsorption: 'SKSK.Skill.Absorb.HeatAbsorption',
    bluntAbsorption: 'SKSK.Skill.Absorb.BluntAbsorption',
    sharpAbsorption: 'SKSK.Skill.Absorb.SharpAbsorption',
    piercingAbsorption: 'SKSK.Skill.Absorb.PiercingAbsorption',
    poisonAbsorption: 'SKSK.Skill.Absorb.PoisonAbsorption',
    acidAbsorption: 'SKSK.Skill.Absorb.AcidAbsorption',
    electricityAbsorption: 'SKSK.Skill.Absorb.ElectricityAbsorption',
    iceAbsorption: 'SKSK.Skill.Absorb.IceAbsorption',
  },
  special: {
    luck: 'SKSK.Skill.Special.Luck',
    massacre: 'SKSK.Skill.Special.Massacre',
    soulforce: 'SKSK.Skill.Special.SoulForce',
    hitCorrection: 'SKSK.Skill.Special.HitCorrection',
    defenseCorrection: 'SKSK.Skill.Special.DefenseCorrection',
    corpusImmortalis: 'SKSK.Skill.Special.CorpusImmortalis',
  }
}